apiVersion: v1
kind: Pod
metadata:
  name: test-ubuntu
  namespace: default
  labels:
    app: test
    runtime: cocoon
  annotations:
    cocoonset.cocoonstack.io/mode: "run"
    cocoonset.cocoonstack.io/storage: "10G"
    cocoonset.cocoonstack.io/managed: "true"
spec:
  nodeName: cocoon-pool
  tolerations:
    - key: "virtual-kubelet.io/provider"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: ubuntu
      image: ubuntu-dev-base
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
